<a href="https://colab.research.google.com/github/B-bori/python/blob/master/0320_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Question 1_answer
from numpy import array
A=array([(3,4), (-1,2)])
B=array([(5,2), (8,-3)])
A*B

array([[15,  8],
       [-8, -6]])

In [0]:
#Question 2_answer
from numpy import array
A=array([(3,4), (-1,2)])
B=array([(5,2), (8,-3)])
A.dot(B)

array([[47, -6],
       [11, -8]])

In [0]:
#Question 3_answer
from numpy import array
A=array([(3,4), (-1,2)])
B=array([(5,2), (8,-3)])
print(inv(A))
print(inv(B))


[[ 0.2 -0.4]
 [ 0.1  0.3]]
[[ 0.09677419  0.06451613]
 [ 0.25806452 -0.16129032]]


In [0]:
#Question 4_answer
import numpy as np
A=array([(3,4), (-1,2)])
np.trace(A)

5

In [0]:
#Question 5_answer
from numpy import array
A=array([1,2,3,4,5])
print(A.ndim)
print(A.shape)

1
(5,)


In [0]:
#Question 6_answer
import numpy as np
a=np.arange(1,10).reshape(3,3)
print(a)
i=int(input())
j=int(input())
A=np.array(a[i-1,:])
B=np.array(a[:,j-1])
print(np.dot(A,B))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
1
30


In [0]:
#Question 7_answer
import numpy as np
A=array([(3,4), (-1,2)])
B=array([(5,2), (8,-3)])
np.dot(A,B)+2*np.dot(B,B)-np.identity(2)

array([[128.,   2.],
       [ 43.,  41.]])

In [0]:
#Question 8_answer
import numpy as np
A=array([(3,4), (-1,2)])
B=array([(5,2), (8,-3)])
print(np.transpose(A))
print(np.transpose(B))

[[ 3 -1]
 [ 4  2]]
[[ 5  8]
 [ 2 -3]]
