<a href="https://colab.research.google.com/github/B-bori/python/blob/master/0327_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from numpy import array
from numpy.linalg import inv 
M = array([
   [1,2,1],
   [4,4,5],
   [6,7,7]
   ])
M_inverse = inv(M)
print(M_inverse)


[[-7. -7.  6.]
 [ 2.  1. -1.]
 [ 4.  5. -4.]]


In [0]:
from numpy import array
from numpy.linalg import solve
A = array([
[2,3,5],
[4,-2,-7],
[9,5,3]
])
B = array([1,8,2])
C = solve(A,B)
print(C)

[  5.86956522 -13.86956522   6.17391304]


In [0]:
from numpy import array
from numpy import vstack
from numpy.linalg import det
v1 = array([1,2,-3,4])
v2 = array([1,1,0,2])
v3 = array([-1,-2,1,1])
M = vstack((v1,v2,v3))
print(det(M))

LinAlgError: ignored

In [0]:
from numpy import array
from numpy.linalg import det
M=array([
        [2,0,1,2,0],
        [2,-1,0,1,1],
        [0,1,2,1,2],
        [-2,0,2,-1,2],
        [2,0,0,1,1]
        ])
print(det(M))

6.000000000000003
ERROR! Session/line number was not unique in database. History logging moved to new session 59


In [0]:
from numpy import array
from numpy.linalg import eig
from numpy.linalg import det
M = array([
[1,0],
[1,1]
])
values, vectors = eig(M)
print(values)
print(vectors)
print((vectors[1][1])**2+(vectors[0][1])**2)

[1. 1.]
[[ 0.00000000e+00  2.22044605e-16]
 [ 1.00000000e+00 -1.00000000e+00]]
1.0


In [0]:
from numpy import array
from numpy.linalg import eig
from numpy.linalg import inv
A=([
[1,2,1],
[4,4,5],
[6,7,7]])
values,vectors = eig(A)
P=vectors
P_inverse=inv(P)
D = P_inverse.dot(A).dot(P)
print(D)

[[ 1.27880923e+01 -1.72627203e-15  2.16624219e-15]
 [ 3.25837454e-15 -1.16422974e-01  1.55886928e-15]
 [ 2.01346697e-15 -1.48295521e-15 -6.71669376e-01]]


In [0]:
from numpy import array
from numpy.linalg import solve
A = array([
[1,1,-1,0],
[2,1,-2,0],
[-3,0,1,0],
[4,2,1,0]
])
B = array([0,0,0,0])
C = solve(A,B)
print(C)

LinAlgError: ignored