<a href="https://colab.research.google.com/github/B-bori/python/blob/master/%5BAns%5D_0320_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

### 1. Write a program to compute the multiplication of the two given matrixes. 

In [0]:
A = np.array([[3,4],[-1,2]])
B = np.array([[5,2],[8,-3]])
np.matmul(A,B)

array([[47, -6],
       [11, -8]])

In [0]:
A = np.matrix([[3,4],[-1,2]])
B = np.matrix([[5,2],[8,-3]])
A*B

matrix([[47, -6],
        [11, -8]])

### 2.Write the dot product of the two given matrixes.

In [0]:
A = np.array([[3,4],[-1,2]])
B = np.array([[5,2],[8,-3]])
np.dot(A,B)

array([[47, -6],
       [11, -8]])

### 3. Write a program to compute the inverse of the two given matrixes. 

In [0]:
A = np.array([[3,4],[-1,2]])
B = np.array([[5,2],[8,-3]])

#inverse of A
A_inv = np.linalg.inv(A)

#inverse of B
B_inv = np.linalg.inv(B)

In [0]:
A_inv

array([[ 0.2, -0.4],
       [ 0.1,  0.3]])

In [0]:
B_inv

array([[ 0.09677419,  0.06451613],
       [ 0.25806452, -0.16129032]])

### 4. Write a program to compute the sum of the diagonal element of a given array

In [0]:
A = np.array([[3,4],[-1,2]])
A

array([[ 3,  4],
       [-1,  2]])

In [0]:
A_diag = np.diag(A)
np.sum(A_diag)

5

### 5. Create a 1D (one-dimensional) NumPy array and verify its dimensions and shape. 

In [0]:
oned = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
print("oned's shape: ",oned.shape)
print("oned's dimension:" , oned.ndim)
print(oned)

oned's shape:  (18,)
oned's dimension: 1
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [0]:
# np.reshape
reshaped = oned.reshape((3,6))
print("reshaped's shape :",reshaped.shape)
print("reshaped's shape :",reshaped.ndim)
print(reshaped)

reshaped's shape : (3, 6)
reshaped's shape : 2
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [0]:
# np.expand_dims()
expandd = np.reshape(oned, (3,3,2))
print("expandd's shape :",expandd.shape)
print("expandd's shape :",expandd.ndim)
print(expandd)

expandd's shape : (3, 3, 2)
expandd's shape : 3
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


### 6. Write a NumPy program to return the dot product of row I and column j (both i and j would be pre-determined) 

In [0]:
# row i
i = np.matrix([1,2,3,4])
print(i.shape)

# col j
col = np.matrix([3,4,5,6])
j = col.T
print(j.shape)

# dot product of i and j
dot = i*j
print(dot)

(1, 4)
(4, 1)
[[50]]


### 7. Compute the matrix equation AB+2B^2− I (I means the identity matrix) for matrices

In [0]:
A = np.matrix([[3,4],[-1,2]])
B = np.matrix([[5,2],[8,-3]])


np.dot(A,B)+(2*(B**2))-np.identity(2)

matrix([[128.,   2.],
        [ 43.,  41.]])

### 8. Compute AT and BT

In [0]:
A = np.matrix([[3,4],[-1,2]])
B = np.matrix([[5,2],[8,-3]])

AT = A.T
BT = B.T

print("AT:")
print(AT)
print("BT:")
print(BT)

AT:
[[ 3 -1]
 [ 4  2]]
BT:
[[ 5  8]
 [ 2 -3]]
